
[general]
import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/font.toml"
]
live_config_reload = true

[terminal]

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[terminal.shell]
program = "/opt/homebrew/bin/zellij"

[window]
decorations = "none"
dynamic_title = true
opacity = 0.95
startup_mode = "Windowed"

[window.dimensions]
columns = 164
lines = 32

[window.padding]
x = 12
y = 12

